// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026, Unikraft GmbH.
// Licensed under the BSD-3-Clause License (the "License").
// You may not use this file except in compliance with the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protoc-gen-go-struct/tags/tags.proto

package tags

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tag represents an arbitrary key-value pair that will be emitted as a Go
// struct tag in the form key:"value".
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_protoc_gen_go_struct_tags_tags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_go_struct_tags_tags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_protoc_gen_go_struct_tags_tags_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var file_protoc_gen_go_struct_tags_tags_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]*Tag)(nil),
		Field:         50102,
		Name:          "com.unikraft.tools.protoc_gen_go_struct.tags",
		Tag:           "bytes,50102,rep,name=tags",
		Filename:      "protoc-gen-go-struct/tags/tags.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// tags specifies additional Go struct tags for this field.
	// Each entry becomes a key:"value" pair in the generated struct tag.
	//
	// repeated com.unikraft.tools.protoc_gen_go_struct.Tag tags = 50102;
	E_Tags = &file_protoc_gen_go_struct_tags_tags_proto_extTypes[0]
)

var File_protoc_gen_go_struct_tags_tags_proto protoreflect.FileDescriptor

const file_protoc_gen_go_struct_tags_tags_proto_rawDesc = "" +
	"\n" +
	"$protoc-gen-go-struct/tags/tags.proto\x12'com.unikraft.tools.protoc_gen_go_struct\x1a google/protobuf/descriptor.proto\"-\n" +
	"\x03Tag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:a\n" +
	"\x04tags\x12\x1d.google.protobuf.FieldOptions\x18\xb6\x87\x03 \x03(\v2,.com.unikraft.tools.protoc_gen_go_struct.TagR\x04tagsB0Z.unikraft.com/x/tools/protoc-gen-go-struct/tagsb\x06proto3"

var (
	file_protoc_gen_go_struct_tags_tags_proto_rawDescOnce sync.Once
	file_protoc_gen_go_struct_tags_tags_proto_rawDescData []byte
)

func file_protoc_gen_go_struct_tags_tags_proto_rawDescGZIP() []byte {
	file_protoc_gen_go_struct_tags_tags_proto_rawDescOnce.Do(func() {
		file_protoc_gen_go_struct_tags_tags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoc_gen_go_struct_tags_tags_proto_rawDesc), len(file_protoc_gen_go_struct_tags_tags_proto_rawDesc)))
	})
	return file_protoc_gen_go_struct_tags_tags_proto_rawDescData
}

var file_protoc_gen_go_struct_tags_tags_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protoc_gen_go_struct_tags_tags_proto_goTypes = []any{
	(*Tag)(nil),                       // 0: com.unikraft.tools.protoc_gen_go_struct.Tag
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_protoc_gen_go_struct_tags_tags_proto_depIdxs = []int32{
	1, // 0: com.unikraft.tools.protoc_gen_go_struct.tags:extendee -> google.protobuf.FieldOptions
	0, // 1: com.unikraft.tools.protoc_gen_go_struct.tags:type_name -> com.unikraft.tools.protoc_gen_go_struct.Tag
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoc_gen_go_struct_tags_tags_proto_init() }
func file_protoc_gen_go_struct_tags_tags_proto_init() {
	if File_protoc_gen_go_struct_tags_tags_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoc_gen_go_struct_tags_tags_proto_rawDesc), len(file_protoc_gen_go_struct_tags_tags_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_protoc_gen_go_struct_tags_tags_proto_goTypes,
		DependencyIndexes: file_protoc_gen_go_struct_tags_tags_proto_depIdxs,
		MessageInfos:      file_protoc_gen_go_struct_tags_tags_proto_msgTypes,
		ExtensionInfos:    file_protoc_gen_go_struct_tags_tags_proto_extTypes,
	}.Build()
	File_protoc_gen_go_struct_tags_tags_proto = out.File
	file_protoc_gen_go_struct_tags_tags_proto_goTypes = nil
	file_protoc_gen_go_struct_tags_tags_proto_depIdxs = nil
}
