name: setup-go

description: Setup all the tools required for our go actions

inputs:
  gh_pat:
    description: GitHub PAT for accessing private repositories
    required: false
  goprivate:
    description: Comma-separated list of module path prefixes for GOPRIVATE and GONOSUMDB
    required: false

runs:
  using: composite
  steps:
    - name: Login to GitHub
      if: ${{ inputs.gh_pat != '' }}
      shell: bash
      run: |
        git config --global url."https://x-access-token:${{ inputs.gh_pat }}@github.com/".insteadOf "https://github.com/"

    - name: Detect Go version file
      id: goversionfile
      shell: bash
      run: |
        if [ -f go.work ]; then
          echo "file=go.work" >>"$GITHUB_OUTPUT"
        else
          echo "file=go.mod" >>"$GITHUB_OUTPUT"
        fi

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: ${{ steps.goversionfile.outputs.file }}
        cache: false

    - name: Set Go variables
      id: goenv
      shell: bash
      run: |
        {
          echo "cache=$(go env GOCACHE)"
          echo "modcache=$(go env GOMODCACHE)"
          echo "mod=$(go env GOMOD)"
        } >>"$GITHUB_OUTPUT"

    - name: Setup GOPRIVATE
      if: ${{ inputs.goprivate != '' }}
      shell: bash
      run: |
        echo "GOPRIVATE=${{ inputs.goprivate }}" >> "$GITHUB_ENV"
        echo "GONOSUMDB=${{ inputs.goprivate }}" >> "$GITHUB_ENV"

    - name: Go caches
      uses: actions/cache@v5
      with:
        path: |
          ${{ steps.goenv.outputs.cache }}
          ${{ steps.goenv.outputs.modcache }}
        key: ${{ github.job }}-${{ runner.os }}-go-${{ hashFiles(steps.goenv.outputs.mod) }}
        restore-keys: |
          ${{ github.job }}-${{ runner.os }}-go-

    - name: Setup Task
      uses: go-task/setup-task@v2

    - name: Enable remote Taskfiles experiment
      shell: bash
      run: |
        echo TASK_X_REMOTE_TASKFILES=1 >>"$GITHUB_ENV"

    # Check that we can resolve remote taskfiles, populate cache and force
    # using that cache instead of the network
    - name: Check Taskfile
      shell: bash
      run: |
        task --verbose --download --yes --list-all
        echo TASK_OFFLINE=1 >>"$GITHUB_ENV"
