// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026, Unikraft GmbH.
// Licensed under the BSD-3-Clause License (the "License").
// You may not use this file except in compliance with the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//	protoc-gen-go v1.36.11
//	protoc        (unknown)
// source: protoc-gen-go-struct/flag/flag.proto

package flag

import (
	"reflect"
	"unsafe"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_protoc_gen_go_struct_flag_flag_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50100,
		Name:          "com.unikraft.tools.protoc_gen_go_struct.flag_name",
		Tag:           "bytes,50100,opt,name=flag_name",
		Filename:      "protoc-gen-go-struct/flag/flag.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50101,
		Name:          "com.unikraft.tools.protoc_gen_go_struct.flag_default",
		Tag:           "bytes,50101,opt,name=flag_default",
		Filename:      "protoc-gen-go-struct/flag/flag.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// flag_name specifies the command-line flag name(s) for this field.
	// Multiple names can be separated by commas (e.g., "--workspace,-w").
	//
	// optional string flag_name = 50100;
	E_FlagName = &file_protoc_gen_go_struct_flag_flag_proto_extTypes[0]
	// flag_default specifies the default value for the command-line flag.
	//
	// optional string flag_default = 50101;
	E_FlagDefault = &file_protoc_gen_go_struct_flag_flag_proto_extTypes[1]
)

var File_protoc_gen_go_struct_flag_flag_proto protoreflect.FileDescriptor

const file_protoc_gen_go_struct_flag_flag_proto_rawDesc = "" +
	"\n" +
	"$protoc-gen-go-struct/flag/flag.proto\x12'com.unikraft.tools.protoc_gen_go_struct\x1a google/protobuf/descriptor.proto:?\n" +
	"\tflag_name\x12\x1d.google.protobuf.FieldOptions\x18\xb4\x87\x03 \x01(\tR\bflagName\x88\x01\x01:E\n" +
	"\fflag_default\x12\x1d.google.protobuf.FieldOptions\x18\xb5\x87\x03 \x01(\tR\vflagDefault\x88\x01\x01B0Z.unikraft.com/x/tools/protoc-gen-go-struct/flagb\x06proto3"

var file_protoc_gen_go_struct_flag_flag_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_protoc_gen_go_struct_flag_flag_proto_depIdxs = []int32{
	0, // 0: com.unikraft.tools.protoc_gen_go_struct.flag_name:extendee -> google.protobuf.FieldOptions
	0, // 1: com.unikraft.tools.protoc_gen_go_struct.flag_default:extendee -> google.protobuf.FieldOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoc_gen_go_struct_flag_flag_proto_init() }
func file_protoc_gen_go_struct_flag_flag_proto_init() {
	if File_protoc_gen_go_struct_flag_flag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoc_gen_go_struct_flag_flag_proto_rawDesc), len(file_protoc_gen_go_struct_flag_flag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_protoc_gen_go_struct_flag_flag_proto_goTypes,
		DependencyIndexes: file_protoc_gen_go_struct_flag_flag_proto_depIdxs,
		ExtensionInfos:    file_protoc_gen_go_struct_flag_flag_proto_extTypes,
	}.Build()
	File_protoc_gen_go_struct_flag_flag_proto = out.File
	file_protoc_gen_go_struct_flag_flag_proto_goTypes = nil
	file_protoc_gen_go_struct_flag_flag_proto_depIdxs = nil
}

// GetFlagName retrieves the flag_name extension value from field options.
// Returns the flag name(s) and true if set, or empty string and false if not set.
func GetFlagName(opts protoreflect.ProtoMessage) (string, bool) {
	if opts == nil {
		return "", false
	}
	ext := proto.GetExtension(opts, E_FlagName)
	if ext == nil {
		return "", false
	}
	if s, ok := ext.(*string); ok && s != nil {
		return *s, true
	}
	if s, ok := ext.(string); ok {
		return s, s != ""
	}
	return "", false
}

// GetFlagDefault retrieves the flag_default extension value from field options.
// Returns the default value and true if set, or empty string and false if not set.
func GetFlagDefault(opts protoreflect.ProtoMessage) (string, bool) {
	if opts == nil {
		return "", false
	}
	ext := proto.GetExtension(opts, E_FlagDefault)
	if ext == nil {
		return "", false
	}
	if s, ok := ext.(*string); ok && s != nil {
		return *s, true
	}
	if s, ok := ext.(string); ok {
		return s, s != ""
	}
	return "", false
}
