// Code generated by unikraft.com/x/tools/openapi-gen. DO NOT EDIT.

package server

import (
	"time"

	"github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
)

// Ensure imports are used.
var (
	_ time.Time
)

type CreateWidgetRequest struct {
	Name string `json:"name" yaml:"name"`
	Size *int   `json:"size,omitzero" yaml:"size,omitempty"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed" yaml:"-"`
}

// UnmarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *CreateWidgetRequest) UnmarshalJSON(data []byte) error {
	type Alias CreateWidgetRequest
	return json.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m CreateWidgetRequest) MarshalJSON() ([]byte, error) {
	type Alias CreateWidgetRequest
	return json.Marshal((Alias)(m))
}

type CreateWidgetResponse struct {
	Data *CreateWidgetResponseData `json:"data,omitzero" yaml:"data,omitempty"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed" yaml:"-"`
}

// UnmarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *CreateWidgetResponse) UnmarshalJSON(data []byte) error {
	type Alias CreateWidgetResponse
	return json.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m CreateWidgetResponse) MarshalJSON() ([]byte, error) {
	type Alias CreateWidgetResponse
	return json.Marshal((Alias)(m))
}

type CreateWidgetResponseData struct {
	Widget *Widget `json:"widget,omitzero" yaml:"widget,omitempty"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed" yaml:"-"`
}

// UnmarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *CreateWidgetResponseData) UnmarshalJSON(data []byte) error {
	type Alias CreateWidgetResponseData
	return json.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m CreateWidgetResponseData) MarshalJSON() ([]byte, error) {
	type Alias CreateWidgetResponseData
	return json.Marshal((Alias)(m))
}

type DeleteWidgetResponse struct {

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed" yaml:"-"`
}

// UnmarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *DeleteWidgetResponse) UnmarshalJSON(data []byte) error {
	type Alias DeleteWidgetResponse
	return json.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m DeleteWidgetResponse) MarshalJSON() ([]byte, error) {
	type Alias DeleteWidgetResponse
	return json.Marshal((Alias)(m))
}

type GetWidgetResponse struct {
	Data *GetWidgetResponseData `json:"data,omitzero" yaml:"data,omitempty"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed" yaml:"-"`
}

// UnmarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *GetWidgetResponse) UnmarshalJSON(data []byte) error {
	type Alias GetWidgetResponse
	return json.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m GetWidgetResponse) MarshalJSON() ([]byte, error) {
	type Alias GetWidgetResponse
	return json.Marshal((Alias)(m))
}

type GetWidgetResponseData struct {
	Widget *Widget `json:"widget,omitzero" yaml:"widget,omitempty"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed" yaml:"-"`
}

// UnmarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *GetWidgetResponseData) UnmarshalJSON(data []byte) error {
	type Alias GetWidgetResponseData
	return json.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m GetWidgetResponseData) MarshalJSON() ([]byte, error) {
	type Alias GetWidgetResponseData
	return json.Marshal((Alias)(m))
}

type ListWidgetsResponse struct {
	Data *ListWidgetsResponseData `json:"data,omitzero" yaml:"data,omitempty"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed" yaml:"-"`
}

// UnmarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *ListWidgetsResponse) UnmarshalJSON(data []byte) error {
	type Alias ListWidgetsResponse
	return json.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m ListWidgetsResponse) MarshalJSON() ([]byte, error) {
	type Alias ListWidgetsResponse
	return json.Marshal((Alias)(m))
}

type ListWidgetsResponseData struct {
	Widgets []Widget `json:"widgets,omitzero" yaml:"widgets,omitempty"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed" yaml:"-"`
}

// UnmarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *ListWidgetsResponseData) UnmarshalJSON(data []byte) error {
	type Alias ListWidgetsResponseData
	return json.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m ListWidgetsResponseData) MarshalJSON() ([]byte, error) {
	type Alias ListWidgetsResponseData
	return json.Marshal((Alias)(m))
}

type Widget struct {
	Id        *string    `json:"id,omitzero" yaml:"id,omitempty"`
	Name      *string    `json:"name,omitzero" yaml:"name,omitempty"`
	Size      *int       `json:"size,omitzero" yaml:"size,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitzero" yaml:"created_at,omitempty"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed" yaml:"-"`
}

// UnmarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *Widget) UnmarshalJSON(data []byte) error {
	type Alias Widget
	return json.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to go-json-experiment so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m Widget) MarshalJSON() ([]byte, error) {
	type Alias Widget
	return json.Marshal((Alias)(m))
}
