// Code generated by unikraft.com/x/tools/openapi-gen. DO NOT EDIT.

package server

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"

	"unikraft.com/x/log"
)

// Ensure imports are used.
var (
	_ = bytes.NewReader
	_ = fmt.Sprintf
	_ = json.Marshal
	_ io.Reader
	_ http.Client
	_ context.Context
	_ = log.New
	_ = time.Now
)

// Widgets provides the API handlers.
type Widgets interface {
	CreateWidget(g *gin.Context, req *CreateWidgetRequest) (*CreateWidgetResponse, int, error)
	DeleteWidget(g *gin.Context, id string) (*DeleteWidgetResponse, int, error)
	GetWidget(g *gin.Context, id string) (*GetWidgetResponse, int, error)
	ListWidgets(g *gin.Context, limit *int) (*ListWidgetsResponse, int, error)
	WatchWidget(g *gin.Context, cancel context.CancelFunc, id string) <-chan *Widget
}

type WidgetsHandler struct {
	service Widgets
	resp    func(*gin.Context, int, any)
}

// Per-operation identifiers for Widgets, for use with WithOperationMiddleware.
const (
	OpCreateWidget = "CreateWidget"
	OpDeleteWidget = "DeleteWidget"
	OpGetWidget    = "GetWidget"
	OpListWidgets  = "ListWidgets"
	OpWatchWidget  = "WatchWidget"
)

// WidgetsRegistration configures and registers the HTTP handlers for the Widgets service.
type WidgetsRegistration struct {
	service      Widgets
	resp         func(*gin.Context, int, any)
	middleware   []gin.HandlerFunc
	opMiddleware map[string][]gin.HandlerFunc
}

// NewWidgetsRegistration creates a WidgetsRegistration, configure it with WithMiddleware and WithOperationMiddleware, then call Register.
func NewWidgetsRegistration(service Widgets, resp func(*gin.Context, int, any)) *WidgetsRegistration {
	return &WidgetsRegistration{
		service:      service,
		resp:         resp,
		opMiddleware: make(map[string][]gin.HandlerFunc),
	}
}

// WithMiddleware adds middleware that runs for every operation in Widgets.
func (r *WidgetsRegistration) WithMiddleware(middleware ...gin.HandlerFunc) *WidgetsRegistration {
	r.middleware = append(r.middleware, middleware...)
	return r
}

// WithOperationMiddleware adds middleware that runs only for operationID, after the service-wide middleware.
func (r *WidgetsRegistration) WithOperationMiddleware(operationID string, middleware ...gin.HandlerFunc) *WidgetsRegistration {
	r.opMiddleware[operationID] = append(r.opMiddleware[operationID], middleware...)
	return r
}

// Register registers the HTTP handlers for the Widgets service on engine.
func (r *WidgetsRegistration) Register(engine gin.IRouter) {
	handler := &WidgetsHandler{
		service: r.service,
		resp:    r.resp,
	}

	group := engine.Group("", r.middleware...)
	group.Handle("POST", "/widgets", append(r.opMiddleware[OpCreateWidget], handler.createWidget)...)
	group.Handle("DELETE", "/widgets/:id", append(r.opMiddleware[OpDeleteWidget], handler.deleteWidget)...)
	group.Handle("GET", "/widgets/:id", append(r.opMiddleware[OpGetWidget], handler.getWidget)...)
	group.Handle("GET", "/widgets", append(r.opMiddleware[OpListWidgets], handler.listWidgets)...)
	group.Handle("GET", "/widgets/:id/events", append(r.opMiddleware[OpWatchWidget], handler.watchWidget)...)
}

// RegisterWidgets registers the HTTP handlers for the Widgets service.
func RegisterWidgets(engine gin.IRouter, service Widgets, resp func(*gin.Context, int, any), middleware ...gin.HandlerFunc) {
	NewWidgetsRegistration(service, resp).WithMiddleware(middleware...).Register(engine)
}

func (handler *WidgetsHandler) createWidget(g *gin.Context) {
	bodyBytes, err := g.GetRawData()
	if err != nil {
		log.G(g.Request.Context()).
			Warn().
			Err(err).
			Msg("failed to read request body")
		if handler.resp != nil {
			handler.resp(g, http.StatusBadRequest, err)
		} else {
			g.JSON(http.StatusBadRequest, gin.H{"message": err.Error()})
		}
		return
	}

	// Restore the body for further use.
	g.Request.Body = io.NopCloser(bytes.NewReader(bodyBytes))

	var req CreateWidgetRequest
	if err := g.ShouldBind(&req); err != nil {
		log.G(g.Request.Context()).
			Warn().
			Err(err).
			Msg("failed to bind request body")
		if handler.resp != nil {
			handler.resp(g, http.StatusBadRequest, err)
		} else {
			g.JSON(http.StatusBadRequest, gin.H{"message": err.Error()})
		}
		return
	}

	// Restore the body for further use.
	g.Request.Body = io.NopCloser(bytes.NewReader(bodyBytes))
	resp, code, err := handler.service.CreateWidget(g, &req)
	if err != nil {
		if handler.resp != nil {
			handler.resp(g, code, err)
		} else {
			g.JSON(code, gin.H{"message": err.Error()})
		}
	} else if handler.resp != nil {
		handler.resp(g, code, resp)
	} else {
		g.JSON(code, resp)
	}
}

func (handler *WidgetsHandler) deleteWidget(g *gin.Context) {

	var params struct {
		Id string `uri:"id"`
	}
	if err := g.ShouldBindUri(&params); err != nil {
		log.G(g.Request.Context()).
			Warn().
			Err(err).
			Msg("failed to bind request body")
		if handler.resp != nil {
			handler.resp(g, http.StatusBadRequest, err)
		} else {
			g.JSON(http.StatusBadRequest, gin.H{"message": err.Error()})
		}
		return
	}
	resp, code, err := handler.service.DeleteWidget(g, params.Id)
	if err != nil {
		if handler.resp != nil {
			handler.resp(g, code, err)
		} else {
			g.JSON(code, gin.H{"message": err.Error()})
		}
	} else if handler.resp != nil {
		handler.resp(g, code, resp)
	} else {
		g.JSON(code, resp)
	}
}

func (handler *WidgetsHandler) getWidget(g *gin.Context) {

	var params struct {
		Id string `uri:"id"`
	}
	if err := g.ShouldBindUri(&params); err != nil {
		log.G(g.Request.Context()).
			Warn().
			Err(err).
			Msg("failed to bind request body")
		if handler.resp != nil {
			handler.resp(g, http.StatusBadRequest, err)
		} else {
			g.JSON(http.StatusBadRequest, gin.H{"message": err.Error()})
		}
		return
	}
	resp, code, err := handler.service.GetWidget(g, params.Id)
	if err != nil {
		if handler.resp != nil {
			handler.resp(g, code, err)
		} else {
			g.JSON(code, gin.H{"message": err.Error()})
		}
	} else if handler.resp != nil {
		handler.resp(g, code, resp)
	} else {
		g.JSON(code, resp)
	}
}

func (handler *WidgetsHandler) listWidgets(g *gin.Context) {
	// Bind query parameters
	var query struct {
		Limit *int `form:"limit"`
	}
	if err := g.ShouldBindQuery(&query); err != nil {
		log.G(g.Request.Context()).
			Warn().
			Err(err).
			Msg("failed to bind query parameters")
		if handler.resp != nil {
			handler.resp(g, http.StatusBadRequest, err)
		} else {
			g.JSON(http.StatusBadRequest, gin.H{"message": err.Error()})
		}
		return
	}
	resp, code, err := handler.service.ListWidgets(g,
		query.Limit)
	if err != nil {
		if handler.resp != nil {
			handler.resp(g, code, err)
		} else {
			g.JSON(code, gin.H{"message": err.Error()})
		}
	} else if handler.resp != nil {
		handler.resp(g, code, resp)
	} else {
		g.JSON(code, resp)
	}
}

func (handler *WidgetsHandler) watchWidget(g *gin.Context) {

	var params struct {
		Id string `uri:"id"`
	}
	if err := g.ShouldBindUri(&params); err != nil {
		log.G(g.Request.Context()).
			Warn().
			Err(err).
			Msg("failed to bind request body")
		if handler.resp != nil {
			handler.resp(g, http.StatusBadRequest, err)
		} else {
			g.JSON(http.StatusBadRequest, gin.H{"message": err.Error()})
		}
		return
	}
	// Handle streaming response with Server-Sent Events (SSE)
	g.Header("Content-Type", "text/event-stream")
	g.Header("Cache-Control", "no-cache")
	g.Header("Connection", "keep-alive")
	g.Header("X-Accel-Buffering", "no") // UKC's proxy is based on NGINX.

	// Send an initial keep-alive comment to establish the connection.
	if _, err := fmt.Fprintf(g.Writer, ": keepalive %s\n", time.Now().Format(time.RFC3339)); err != nil {
		log.G(g.Request.Context()).
			Warn().
			Err(err).
			Msg("failed to send keepalive")
	}

	// Create a cancellable context
	streamCtx, cancel := context.WithCancel(g.Request.Context())
	defer cancel()

	// Update the request context to the cancellable one
	g.Request = g.Request.WithContext(streamCtx)

	// Call the service method to get the stream channels
	dataCh := handler.service.WatchWidget(g, cancel, params.Id)

	// Flush headers after calling the service.
	g.Writer.Flush()

	// Set up a heartbeat to keep the connection alive
	ticker := time.NewTicker(30 * time.Second)
	defer ticker.Stop()

	// Send the events to the client
	for {
		select {
		case <-g.Request.Context().Done():
			// Client disconnected
			cancel()
			return

		case <-streamCtx.Done():
			// Context was cancelled or deadline exceeded
			return

		case <-ticker.C:
			// Send a comment as a keepalive
			if _, err := fmt.Fprintf(g.Writer, ": keepalive %s\n", time.Now().Format(time.RFC3339)); err != nil {
				log.G(g.Request.Context()).
					Warn().
					Err(err).
					Msg("failed to send keepalive")
				return
			}
			g.Writer.Flush()

		case data, ok := <-dataCh:
			if !ok {
				// Channel closed
				return
			}

			// Convert the data to JSON
			jsonData, err := json.Marshal(data)
			if err != nil {
				log.G(g.Request.Context()).
					Warn().
					Err(err).
					Msg("failed to marshal event data")
				continue
			}

			// Send the event
			if _, err := fmt.Fprintf(g.Writer, "data: %s\n", jsonData); err != nil {
				log.G(g.Request.Context()).
					Warn().
					Err(err).
					Msg("failed to send event")
				return
			}
			g.Writer.Flush()
		}
	}
}
