// Code generated by unikraft.com/x/tools/openapi-gen. DO NOT EDIT.

package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/url"
	"strings"
)

// Ensure imports are used.
var (
	_ = bytes.NewReader
	_ = strings.TrimSpace
	_ = fmt.Sprintf
	_ = json.Marshal
	_ io.Reader
)

// genericService handles operations without a dedicated tag.
type genericService struct {
	client *Client
}

// WidgetsService provides access to Widgets operations.
type WidgetsService struct {
	client *Client
}

// CreateWidget
func (s *WidgetsService) CreateWidget(ctx context.Context, body *CreateWidgetRequest) (*CreateWidgetResponse, error) {
	pathParams := map[string]string{}
	reqPath := buildPath("/widgets", pathParams)

	q := url.Values{}
	if len(q) > 0 {
		reqPath = reqPath + "?" + q.Encode()
	}

	var bodyReader io.Reader
	if body != nil {
		bodyBytes, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal request body: %w", err)
		}
		bodyReader = bytes.NewReader(bodyBytes)
	}

	req, err := s.client.newRequest(ctx, "POST", reqPath, bodyReader)
	if err != nil {
		return nil, err
	}

	var result CreateWidgetResponse
	_, err = s.client.do(req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteWidget
func (s *WidgetsService) DeleteWidget(ctx context.Context, id string) (*DeleteWidgetResponse, error) {
	pathParams := map[string]string{
		"id": fmt.Sprintf("%v", id),
	}
	reqPath := buildPath("/widgets/{id}", pathParams)

	q := url.Values{}
	if len(q) > 0 {
		reqPath = reqPath + "?" + q.Encode()
	}

	req, err := s.client.newRequest(ctx, "DELETE", reqPath, nil)
	if err != nil {
		return nil, err
	}

	var result DeleteWidgetResponse
	_, err = s.client.do(req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetWidget
func (s *WidgetsService) GetWidget(ctx context.Context, id string) (*GetWidgetResponse, error) {
	pathParams := map[string]string{
		"id": fmt.Sprintf("%v", id),
	}
	reqPath := buildPath("/widgets/{id}", pathParams)

	q := url.Values{}
	if len(q) > 0 {
		reqPath = reqPath + "?" + q.Encode()
	}

	req, err := s.client.newRequest(ctx, "GET", reqPath, nil)
	if err != nil {
		return nil, err
	}

	var result GetWidgetResponse
	_, err = s.client.do(req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ListWidgetsOpts contains optional parameters for ListWidgets.
type ListWidgetsOpts struct {
	Limit *int
}

// ListWidgets
func (s *WidgetsService) ListWidgets(ctx context.Context, opts *ListWidgetsOpts) (*ListWidgetsResponse, error) {
	pathParams := map[string]string{}
	reqPath := buildPath("/widgets", pathParams)

	q := url.Values{}
	if opts != nil && opts.Limit != nil {
		addQueryParam(q, "limit", *opts.Limit)
	}
	if len(q) > 0 {
		reqPath = reqPath + "?" + q.Encode()
	}

	req, err := s.client.newRequest(ctx, "GET", reqPath, nil)
	if err != nil {
		return nil, err
	}

	var result ListWidgetsResponse
	_, err = s.client.do(req, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// WatchWidget
func (s *WidgetsService) WatchWidget(ctx context.Context, id string) error {
	pathParams := map[string]string{
		"id": fmt.Sprintf("%v", id),
	}
	reqPath := buildPath("/widgets/{id}/events", pathParams)

	q := url.Values{}
	if len(q) > 0 {
		reqPath = reqPath + "?" + q.Encode()
	}

	req, err := s.client.newRequest(ctx, "GET", reqPath, nil)
	if err != nil {
		return err
	}

	_, err = s.client.do(req, nil)
	return err
}
