// Code generated by unikraft.com/x/tools/openapi-gen. DO NOT EDIT.

package client

import (
	"encoding/json"
	"encoding/json/jsontext"
	jsonv2 "encoding/json/v2"
	"time"
)

// Prevent unused import errors.
var (
	_ = time.Time{}
	_ = json.Marshal
	_ = jsonv2.Marshal
)

// CreateWidgetRequest defines the CreateWidgetRequest type.
type CreateWidgetRequest struct {
	Name string `json:"name,omitzero"`
	Size *int   `json:"size,omitzero"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed"`
}

// UnmarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *CreateWidgetRequest) UnmarshalJSON(data []byte) error {
	type Alias CreateWidgetRequest
	return jsonv2.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m CreateWidgetRequest) MarshalJSON() ([]byte, error) {
	type Alias CreateWidgetRequest
	return jsonv2.Marshal((Alias)(m))
}

// CreateWidgetResponse defines the CreateWidgetResponse type.
type CreateWidgetResponse struct {
	Data *CreateWidgetResponseData `json:"data,omitzero"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed"`
}

// UnmarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *CreateWidgetResponse) UnmarshalJSON(data []byte) error {
	type Alias CreateWidgetResponse
	return jsonv2.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m CreateWidgetResponse) MarshalJSON() ([]byte, error) {
	type Alias CreateWidgetResponse
	return jsonv2.Marshal((Alias)(m))
}

// CreateWidgetResponseData defines the CreateWidgetResponseData type.
type CreateWidgetResponseData struct {
	Widget *Widget `json:"widget,omitzero"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed"`
}

// UnmarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *CreateWidgetResponseData) UnmarshalJSON(data []byte) error {
	type Alias CreateWidgetResponseData
	return jsonv2.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m CreateWidgetResponseData) MarshalJSON() ([]byte, error) {
	type Alias CreateWidgetResponseData
	return jsonv2.Marshal((Alias)(m))
}

// DeleteWidgetResponse defines the DeleteWidgetResponse type.
type DeleteWidgetResponse struct {

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed"`
}

// UnmarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *DeleteWidgetResponse) UnmarshalJSON(data []byte) error {
	type Alias DeleteWidgetResponse
	return jsonv2.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m DeleteWidgetResponse) MarshalJSON() ([]byte, error) {
	type Alias DeleteWidgetResponse
	return jsonv2.Marshal((Alias)(m))
}

// GetWidgetResponse defines the GetWidgetResponse type.
type GetWidgetResponse struct {
	Data *GetWidgetResponseData `json:"data,omitzero"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed"`
}

// UnmarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *GetWidgetResponse) UnmarshalJSON(data []byte) error {
	type Alias GetWidgetResponse
	return jsonv2.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m GetWidgetResponse) MarshalJSON() ([]byte, error) {
	type Alias GetWidgetResponse
	return jsonv2.Marshal((Alias)(m))
}

// GetWidgetResponseData defines the GetWidgetResponseData type.
type GetWidgetResponseData struct {
	Widget *Widget `json:"widget,omitzero"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed"`
}

// UnmarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *GetWidgetResponseData) UnmarshalJSON(data []byte) error {
	type Alias GetWidgetResponseData
	return jsonv2.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m GetWidgetResponseData) MarshalJSON() ([]byte, error) {
	type Alias GetWidgetResponseData
	return jsonv2.Marshal((Alias)(m))
}

// ListWidgetsResponse defines the ListWidgetsResponse type.
type ListWidgetsResponse struct {
	Data *ListWidgetsResponseData `json:"data,omitzero"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed"`
}

// UnmarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *ListWidgetsResponse) UnmarshalJSON(data []byte) error {
	type Alias ListWidgetsResponse
	return jsonv2.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m ListWidgetsResponse) MarshalJSON() ([]byte, error) {
	type Alias ListWidgetsResponse
	return jsonv2.Marshal((Alias)(m))
}

// ListWidgetsResponseData defines the ListWidgetsResponseData type.
type ListWidgetsResponseData struct {
	Widgets []Widget `json:"widgets,omitzero"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed"`
}

// UnmarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *ListWidgetsResponseData) UnmarshalJSON(data []byte) error {
	type Alias ListWidgetsResponseData
	return jsonv2.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m ListWidgetsResponseData) MarshalJSON() ([]byte, error) {
	type Alias ListWidgetsResponseData
	return jsonv2.Marshal((Alias)(m))
}

// Widget defines the Widget type.
type Widget struct {
	Id        *string    `json:"id,omitzero"`
	Name      *string    `json:"name,omitzero"`
	Size      *int       `json:"size,omitzero"`
	CreatedAt *time.Time `json:"created_at,omitzero"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed"`
}

// UnmarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *Widget) UnmarshalJSON(data []byte) error {
	type Alias Widget
	return jsonv2.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m Widget) MarshalJSON() ([]byte, error) {
	type Alias Widget
	return jsonv2.Marshal((Alias)(m))
}

// JSON is a raw JSON value.
type JSON = json.RawMessage
