name: check/static

on:
  pull_request:
    branches: [prod-staging]
    paths:
      - '**'
      - '!.github/**'
      - .github/workflows/check-static.yaml

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  go:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos:
          - linux
          - darwin
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.work'
          cache: false

      - name: Set Go variables
        id: goenv
        run: |
          {
            echo "cache=$(go env GOCACHE)"
            echo "modcache=$(go env GOMODCACHE)"
            echo "mod=$(go env GOMOD)"
          } >>"$GITHUB_OUTPUT"

      - name: Go caches
        uses: actions/cache@v5
        with:
          path: |
            ${{ steps.goenv.outputs.cache }}
            ${{ steps.goenv.outputs.modcache }}
          key: ${{ github.job }}-${{ runner.os }}-go-${{ hashFiles(steps.goenv.outputs.mod) }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-go-

      - name: Check that go.mods are tidy
        if: matrix.goos == 'linux'
        shell: bash
        run: |
          go work edit -json | jq -r '[.Use[].DiskPath] | sort | .[]' | xargs -I "{}" sh -c "cd {} && go mod tidy"

          git diff --exit-code -- go.work go.work.sum
          # shellcheck disable=SC2046 # this is completely intentional
          git diff --exit-code -- $(go work edit -json | jq -r '[.Use[].DiskPath] | sort | .[]')

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        env:
          GOOS: ${{ matrix.goos }}
        with:
          version: latest
          args: -- $(go work edit -json | jq -c -r '[.Use[].DiskPath] | map_values(. + "/...")[]')
          skip-cache: true
