name: std
permissions:
  contents: read

on:
  pull_request:
    branches: [prod-staging]
    paths:
      - '**'
      - '!.github/**'
      - .github/workflows/std.yaml

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.work'
          cache: false

      - name: Set Go variables
        id: goenv
        run: |
          {
            echo "cache=$(go env GOCACHE)"
            echo "modcache=$(go env GOMODCACHE)"
            echo "mod=$(go env GOMOD)"
          } >>"$GITHUB_OUTPUT"

      - name: Go caches
        uses: actions/cache@v5
        with:
          path: |
            ${{ steps.goenv.outputs.cache }}
            ${{ steps.goenv.outputs.modcache }}
          key: ${{ github.job }}-${{ runner.os }}-go-${{ hashFiles(steps.goenv.outputs.mod) }}
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-go-

      - uses: go-task/setup-task@v1

      - name: Install test prerequisites
        shell: bash
        run: |
          go install github.com/bufbuild/buf/cmd/buf@v1.54.0

      - name: Run checks
        shell: bash
        run: |
          task ci/check

      - name: Run tests
        shell: bash
        run: |
          task ci/test
