name: std
permissions:
  contents: read

on:
  pull_request:
    branches: [prod-staging]
    paths:
      - '**'
      - '!.github/**'
      - .github/workflows/std.yaml

  workflow_call:

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  go:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos:
          - linux
          - darwin
    steps:
      - uses: actions/checkout@v7

      - name: Setup go
        uses: unikraft-cloud/x/.github/actions/setup-go@prod-staging

      - name: Run checks
        shell: bash
        run: |
          task ci/check

      - name: Install test prerequisites
        shell: bash
        run: |
          go install github.com/bufbuild/buf/cmd/buf@v1.54.0

      - name: Run tests
        shell: bash
        run: |
          task ci/test
