name: tools

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [prod-staging]
    paths:
      - 'tools/**'
      - 'Taskfile.yml'
      - 'Taskfile.go.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
        - tool: protoc-gen-go-gin
        - tool: protoc-gen-go-struct

    steps:
    - uses: actions/checkout@v7

    - name: Setup go
      uses: ./.github/actions/setup-go

    - name: Build ${{ matrix.tool }}
      shell: bash
      run: task ${{ matrix.tool }}
